### ISSUE TITLE
`KeyError` in deleting time coordinate in post-processing step of prognostic run

### ISSUE THREAD

**Issue by spencerkclark** [ai2cm/fv3net#1241]
I'm a bit puzzled over why this occurred during a recent prognostic run.  It could just be a transient issue, but I'm logging it here in case it happens again.  Maybe there is some sort of race condition in an underlying library?

```
Traceback (most recent call last):
  File "/usr/local/bin/append_run", line 33, in <module>
    sys.exit(load_entry_point('fv3post', 'console_scripts', 'append_run')())
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/fv3net/workflows/post_process_run/fv3post/append.py", line 291, in append_segment
    append_zarr_along_time(tmp_rundir_file, destination_file, fs)
  File "/fv3net/workflows/post_process_run/fv3post/append.py", line 245, in append_zarr_along_time
    _overwrite_time_array_with_single_chunk(target_path, merged_time, dim)
  File "/fv3net/workflows/post_process_run/fv3post/append.py", line 209, in _overwrite_time_array_with_single_chunk
    del zarr.open_group(fsspec.get_mapper(target))[dim]
  File "/usr/local/lib/python3.6/dist-packages/zarr/hierarchy.py", line 355, in __delitem__
    return self._write_op(self._delitem_nosync, item)
  File "/usr/local/lib/python3.6/dist-packages/zarr/hierarchy.py", line 661, in _write_op
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/zarr/hierarchy.py", line 361, in _delitem_nosync
    rmdir(self._store, path)
  File "/usr/local/lib/python3.6/dist-packages/zarr/storage.py", line 124, in rmdir
    _rmdir_from_keys(store, path)
  File "/usr/local/lib/python3.6/dist-packages/zarr/storage.py", line 111, in _rmdir_from_keys
    del store[key]
  File "/usr/local/lib/python3.6/dist-packages/fsspec/mapping.py", line 165, in __delitem__
    del store[key]
  File "/usr/local/lib/python3.6/dist-packages/fsspec/mapping.py", line 165, in __delitem__
    raise KeyError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/fsspec/mapping.py", line 163, in __delitem__
    self.fs.rm(self._key_to_str(key))
  File "/usr/local/lib/python3.6/dist-packages/fsspec/asyn.py", line 72, in wrapper
    return sync(self.loop, func, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/fsspec/asyn.py", line 53, in sync
    raise result[0]
  File "/usr/local/lib/python3.6/dist-packages/fsspec/asyn.py", line 20, in _runner
    result[0] = await coro
  File "/usr/local/lib/python3.6/dist-packages/gcsfs/core.py", line 833, in _rm
    raise exs[0]
  File "/usr/local/lib/python3.6/dist-packages/gcsfs/core.py", line 816, in _rm_files
    raise OSError(out)
OSError: {'Backend Error'}
```

**Comment by oliverwm1** [comment]
Yeah that is strange, have not seen it before. Thanks for logging it.

**Comment by spencerkclark** [comment]
I hit this again in a recent run: `n2f-25km-specific-climate-ml-unperturbed-tq-rf-fluxes-s2-run-808220673`.

**Comment by spencerkclark** [comment]
I encountered this again in `restart-prognostic-run-gb5fr-3039322593`.  This has happened enough times now that I may try and look into it more.

**Comment by spencerkclark** [comment]
Huh this happened again after a few segments in `restart-prognostic-run-4ml9v-2068665740`.  Here's a [link](https://github.com/ai2cm/explore/blob/master/spencerc/2021-09-27-fsspec-delete-issue/2021-09-27-rollback-diagnostics.ipynb) to a notebook with some code one can use to reset the diagnostics stores after an error like this.

**Comment by spencerkclark** [comment]
This hasn't happened to me in some time, so I think this is safe to close.
