### ISSUE TITLE
Error with HighLevel config in microphysics project script

### ISSUE THREAD

**Issue by frodre** [ai2cm/fv3net#1467]
Just tried to run the prognostic run and got this error, maybe from a recent update.
```
> python scripts/prognostic_run.py --config-path configs/baseline.yaml --duration 3hr

...

INFO:runtime.segmented_run.api:Setting up segmented run at gs://vcm-ml-scratch/2021-10-14-microphsyics-emulation-paper/2021-11-02/bdd92c1f0c2e45819335c6ec168b19f7
Traceback (most recent call last):
  File "scripts/prognostic_run.py", line 80, in <module>
    api.create(url, config)
  File "/fv3net/workflows/prognostic_c48_run/runtime/segmented_run/api.py", line 23, in create
    validate_chunks(fv3config_dict)
  File "/fv3net/workflows/prognostic_c48_run/runtime/segmented_run/validate.py", line 20, in validate_chunks
    user_config: UserConfig = dacite.from_dict(UserConfig, config_dict)
  File "/usr/local/lib/python3.8/dist-packages/dacite/core.py", line 59, in from_dict
    field_data = data[field.name]
TypeError: 'HighLevelConfig' object is not subscriptable
```

**Comment by frodre** [comment]
Resolved by #1459
