### ISSUE TITLE
Antarctic selection transform broken

### ISSUE THREAD

**Issue by frodre** [ai2cm/fv3net#1617]
Using the Antarctic selection in the emulation load transform pipeline now fails on tiles with no Antarctic points.  Indexing zero length slices on netCDF doesn't work, so a `microphysics_traning.py` with `antarctica_only=True` in the config fails.

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/xarray/backends/netCDF4_.py", line 104, in _getitem
    array = getitem(original_array, key)
  File "netCDF4/_netCDF4.pyx", line 4428, in netCDF4._netCDF4.Variable.__getitem__
  File "/usr/local/lib/python3.8/dist-packages/netCDF4/utils.py", line 467, in _out_array_shape
    c = count[..., i].ravel()[0] # All elements should be identical.
IndexError: index 0 is out of bounds for axis 0 with size 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test_select.py", line 9, in <module>
    data.isel({"sample": mask}).load()
  File "/usr/local/lib/python3.8/dist-packages/xarray/core/dataset.py", line 873, in load
    v.load()
  File "/usr/local/lib/python3.8/dist-packages/xarray/core/variable.py", line 451, in load
    self._data = np.asarray(self._data)
  File "/usr/local/lib/python3.8/dist-packages/numpy/core/_asarray.py", line 83, in asarray
    return array(a, dtype, copy=False, order=order)
  File "/usr/local/lib/python3.8/dist-packages/xarray/core/indexing.py", line 548, in __array__
    self._ensure_cached()
  File "/usr/local/lib/python3.8/dist-packages/xarray/core/indexing.py", line 545, in _ensure_cached
    self.array = NumpyIndexingAdapter(np.asarray(self.array))
  File "/usr/local/lib/python3.8/dist-packages/numpy/core/_asarray.py", line 83, in asarray
    return array(a, dtype, copy=False, order=order)
  File "/usr/local/lib/python3.8/dist-packages/xarray/core/indexing.py", line 518, in __array__
    return np.asarray(self.array, dtype=dtype)
  File "/usr/local/lib/python3.8/dist-packages/numpy/core/_asarray.py", line 83, in asarray
    return array(a, dtype, copy=False, order=order)
  File "/usr/local/lib/python3.8/dist-packages/xarray/core/indexing.py", line 419, in __array__
    return np.asarray(array[self.key], dtype=None)
  File "/usr/local/lib/python3.8/dist-packages/xarray/backends/netCDF4_.py", line 91, in __getitem__
    return indexing.explicit_indexing_adapter(
  File "/usr/local/lib/python3.8/dist-packages/xarray/core/indexing.py", line 710, in explicit_indexing_adapter
    result = raw_indexing_method(raw_key.tuple)
  File "/usr/local/lib/python3.8/dist-packages/xarray/backends/netCDF4_.py", line 114, in _getitem
    raise IndexError(msg)
IndexError: The indexing operation you are attempting to perform is not valid on netCDF4.Variable object. Try loading your data into memory first by calling .load().
```

`xarray` and `netcdf4` haven't been changed in the constraints in almost half a year, so I'm not sure what triggered the difference.

**Comment by frodre** [comment]
Old issue where this failure message was discussed, but for a different netCDF issue.
https://github.com/pydata/xarray/issues/593

**Comment by frodre** [comment]
Example that reproduces this error.  

```
import xarray as xr
import numpy as np
from os.path import join
import pdb
import tempfile


da = xr.DataArray(data=np.random.randn(10, 5), dims=["sample", "z"])
lat = xr.DataArray(data=np.ones(10), dims="sample")
ds = xr.Dataset(data_vars={"field": da, "lat": lat})

with tempfile.TemporaryDirectory() as tmpdir:
    filename = join(tmpdir, "test.nc")
    ds.to_netcdf(filename)

    loaded = xr.open_dataset(filename)
    mask = loaded["lat"] == 0  # all false
    pdb.set_trace()
    loaded.isel({"sample": mask}).load()
```

**Comment by frodre** [comment]
Here's the dataset summary if I call `.load()` prior to the selection.

```
data.isel({"sample": mask})
<xarray.Dataset>
Dimensions:                (sample: 0, z: 79)
Coordinates:
    time                   object 2016-03-12 14:45:00
    tile                   int64 4
Dimensions without coordinates: sample, z
Data variables:
    latitude               (sample) float32 
    air_temperature_input  (sample, z) float32 
```

Easiest fix is to probably eagerly load all netCDFs, but that's not very efficient to just turn around and throw out all data.
