### ISSUE TITLE
piggy backed diagnostics fail with new log format

### ISSUE THREAD

**Issue by nbren12** [ai2cm/fv3net#1764]
```
wandb: Synced true-capybara-2209: https://wandb.ai/ai2cm/microphysics-emulation/runs/11kgv7ny

Traceback (most recent call last):
  File "/opt/conda/envs/fv3net/bin/prognostic_run_diags", line 33, in <module>
    sys.exit(load_entry_point('fv3net-diagnostics', 'console_scripts', 'prognostic_run_diags')())
  File "/home/jovyan/fv3net/workflows/diagnostics/fv3net/diagnostics/prognostic_run/cli.py", line 38, in main
    args.func(dissoc(args, "func"))
  File "/home/jovyan/fv3net/workflows/diagnostics/fv3net/diagnostics/prognostic_run/emulation/single_run.py", line 370, in main
    return upload_diagnostics_for_tag(args.tag, summary_only=args.summary_only)
  File "/home/jovyan/fv3net/workflows/diagnostics/fv3net/diagnostics/prognostic_run/emulation/single_run.py", line 366, in upload_diagnostics_for_tag
    upload_diagnostics_for_rundir(url, summary_only)
  File "/home/jovyan/fv3net/workflows/diagnostics/fv3net/diagnostics/prognostic_run/emulation/single_run.py", line 320, in upload_diagnostics_for_rundir
    log_summary("duration_seconds", get_duration_seconds(url))
  File "/home/jovyan/fv3net/workflows/diagnostics/fv3net/diagnostics/prognostic_run/emulation/single_run.py", line 265, in get_duration_seconds
    return parse_duration(logs).total_seconds()
  File "/home/jovyan/fv3net/workflows/diagnostics/fv3net/diagnostics/prognostic_run/logs.py", line 14, in parse_duration
    last_time = profile_time[-1]
IndexError: list index out of range
```

**Comment by nbren12** [comment]
Fixed by c67adf7409f7ab5e94b94e64e99ae0ae312a12a5
