### ISSUE TITLE
Prognostic run error: attempts to use getter for a ML prephysics output during postphysics update

### ISSUE THREAD

**Issue by AnnaKwa** [ai2cm/fv3net#1811]
https://console.cloud.google.com/logs/query;query=%22multiyear-climat-sst-stable-mae-prog-run-7333a4b7616a-2544845185%22;timeRange=2022-04-28T18:21:00.883Z%2F2022-04-28T19:21:00.883Z;cursorTimestamp=2022-04-28T19:20:35.088346007Z?project=vcm-ml&folder=true&organizationId=916291154139

A strange new error has popped up when using a radiative flux model in a prognostic run on a more recent commit ffe4f5a3ee699c0f16aa32aa3603c6325de34d22. This does not appear in prognostic runs using the same ML radiative flux model on an older commit 178bcfb61aa144def2249027e577e61a71996c54.

The full trace is pasted below. The error occurs in the postphysics step although the key error occurs for a variable that is an output of the ML prephysics model. Something must be going wrong such that the prephysics radiative flux state updates to `override_for_time_adjusted_...` are still in the state update dict at the post physics step.  Either i) the renaming to the prephysics state update variables `override_for_time_adjusted_...` isn't happening correctly (even though this part of the config hasn't changed before/after the breakage) or ii) the prephysics state updates aren't getting dissociated out of the state update dict correctly.

The other confusing thing is that even if the state updates from the prephysics ML prediction are applied in the postphysics step, the key error occurs because the getter tries to access the ML predicted variable `shortwave_transmissivity_of_atmospheric_column` from the state, which doesn't seem like it'd be an issue if the state update field was coming from the output of the MLStepper. 

Debugging this has been challenging because I can't seem to reproduce this error when using the same prognostic run image locally (see https://github.com/ai2cm/fv3net/issues/1810)

```
Traceback (most recent call last):
  File "/fv3net/workflows/prognostic_c48_run/runtime/derived_state.py", line 42, in __getitem__
    return self._getter.get_state([key])[key].data_array
  File "lib/_wrapper.pyx", line 1785, in fv3gfs.wrapper._wrapper.get_state
pace.util._exceptions.InvalidQuantityError: Quantity shortwave_transmissivity_of_atmospheric_column does not exist - is there a typo?

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.8/dist-packages/mpi4py/__main__.py", line 7, in <module>
    main()
  File "/usr/local/lib/python3.8/dist-packages/mpi4py/run.py", line 196, in main
    run_command_line(args)
  File "/usr/local/lib/python3.8/dist-packages/mpi4py/run.py", line 47, in run_command_line
    run_path(sys.argv[0], run_name='__main__')
  File "/usr/lib/python3.8/runpy.py", line 265, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/usr/lib/python3.8/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/fv3net/workflows/prognostic_c48_run/runtime/main.py", line 77, in <module>
    main()
  File "/fv3net/workflows/prognostic_c48_run/runtime/main.py", line 50, in main
    for time, diagnostics in loop:
  File "/fv3net/workflows/prognostic_c48_run/runtime/loop.py", line 552, in __iter__
    diagnostics.update(substep())
  File "/fv3net/workflows/prognostic_c48_run/runtime/monitor.py", line 54, in step
    diags = func()
  File "/fv3net/workflows/prognostic_c48_run/runtime/loop.py", line 515, in _apply_postphysics_to_dycore_state
    self._state.update_mass_conserving(self._state_updates)
  File "/fv3net/workflows/prognostic_c48_run/runtime/derived_state.py", line 168, in update_mass_conserving
    self.left.update_mass_conserving(items)
  File "/fv3net/workflows/prognostic_c48_run/runtime/derived_state.py", line 117, in update_mass_conserving
    items_with_attrs = _cast_single_to_double(self._assign_attrs_from_mapper(items))
  File "/fv3net/workflows/prognostic_c48_run/runtime/derived_state.py", line 135, in _assign_attrs_from_mapper
    updated[name] = dst[name].assign_attrs(self._mapper[name].attrs)
  File "/usr/local/lib/python3.8/dist-packages/vcm/derived_mapping.py", line 64, in __getitem__
    return self.VARIABLES[key](self)
  File "/usr/local/lib/python3.8/dist-packages/vcm/derived_mapping.py", line 223, in downward_shortwave_sfc_flux_via_transmissivity
    transmissivity = self["shortwave_transmissivity_of_atmospheric_column"]
  File "/usr/local/lib/python3.8/dist-packages/vcm/derived_mapping.py", line 66, in __getitem__
    return self._mapper[key]
  File "/fv3net/workflows/prognostic_c48_run/runtime/derived_state.py", line 44, in __getitem__
    raise KeyError(e)
KeyError: InvalidQuantityError('Quantity shortwave_transmissivity_of_atmospheric_column does not exist - is there a typo?')
```

**Comment by AnnaKwa** [comment]
Apparently the bug in the step metadata commit that was fixed in 
https://github.com/ai2cm/fv3net/commit/dbff1d85239463aae0200328f2ac2f0bc1925c8e caused this. The error does not occur in versions of master after this fix commit. It's strange cause I thought the bug in the original step metadata commit was just an issue of forgetting that None could be a value in config dict. Apparently there was another issue there, with the following code block (now gone) modifying the scikit_learn section to insert the prephysics ML model in its list of models.

```
    urls = config_dict.get("scikit_learn", {}).get("model", [])
    prephysics_config = config_dict.get("prephysics", [])
    for entry in prephysics_config:
        urls += entry.get("model", [])
```
I didn't know `.get` could modify the dict in place like that 😮
