### ISSUE TITLE
Cryptic error message when physics output frequency is mis configured

### ISSUE THREAD

**Issue by nbren12** [ai2cm/fv3net#1824]
I recently came across the error:
```
Traceback (most recent call last):
  File "scripts/test_config.py", line 11, in <module>
    config_fv3config = config.to_fv3config()
  File "/usr/local/lib/python3.8/dist-packages/runtime/segmented_run/prepare_config.py", line 178, in to_fv3config
    file_configs_to_namelist_settings(
  File "/usr/local/lib/python3.8/dist-packages/runtime/diagnostics/fortran.py", line 158, in file_configs_to_namelist_settings
    raise NotImplementedError(
NotImplementedError: Cannot output physics diagnostics at multiple frequencies.
```
which is not very helpful. It should say what settings I should change.

**Comment by nbren12** [comment]
Or maybe this configuration should be changed so that there is only a single global configuration.

@spencerkclark How hard would it be to let the fortran use different output frequencies for the physics?

**Comment by nbren12** [comment]
cc @oliverwm1

**Comment by spencerkclark** [comment]
For some variables it is already enabled but we'd just need to modify their "module" so that this code in fv3net doesn't flag them as a problem (https://github.com/ai2cm/fv3gfs-fortran/issues/175).

For the more standard physics diagnostics like the radiative fluxes, precipitation, surface temperature, etc., it would be a bit of a project to make sure that you could obtain identical results.  Some are simple to convert, others require more care, e.g. the radiative flux diagnostics in particular (I looked into doing this a couple years ago).  If we wanted to do it a few key diagnostics at a time it could be manageable, however.

**Comment by nbren12** [comment]
oh interesting. I encountered this error when trying to save the 3d physics tendency diagnostics at a different interval from the lhf, so the "retagging" mentioned in that issue is directly applicable.

**Comment by oliverwm1** [comment]
Alternatively, @spencerkclark do you think there is another way we could specify which variables are subject to this constraint? Could potentially have a more specific database of variable names instead of relying on module names.

Either way, a more specific error message would be straightforward to implement.

**Comment by spencerkclark** [comment]
Yeah, we could do something like that instead.  It would prevent the need to update any existing diag_tables, which might be nice.  The most expedient thing would probably be to create a list of exceptions to this rule -- currently I think the only ones are the per-physics component tendencies -- and allow those to pass through without any restrictions.
