### ISSUE TITLE
`make lock_pip` fails with distutils AssertionError

### ISSUE THREAD

**Issue by oliverwm1** [ai2cm/fv3net#1924]
Whether on my mac or my VM, running `make lock_pip` fails with:

```
(fv3net) oliverwm@Oliver-WattMeyers-MacBook-Pro fv3net % make lock_pip        
docker run -ti --entrypoint="pip" apache/beam_python3.8_sdk:2.37.0 freeze \
        | sed 's/apache-beam.*/apache-beam=='2.37.0'/' \
        | grep -v google-python-cloud-debugger \
        > .dataflow-versions.txt
pip-compile  \
--no-annotate \
.dataflow-versions.txt \
external/vcm/setup.py pip-requirements.txt external/fv3kube/setup.py external/fv3fit/setup.py external/fv3gfs-fortran.requirements.in workflows/post_process_run/requirements.txt workflows/prognostic_c48_run/requirements.in projects/microphysics/requirements.in \
--output-file constraints.txt
/Users/oliverwm/miniconda3/envs/fv3net/lib/python3.8/site-packages/_distutils_hack/__init__.py:17: UserWarning: Distutils was imported before Setuptools, but importing Setuptools also replaces the `distutils` module in `sys.modules`. This may lead to undesirable behaviors or errors. To avoid these issues, avoid using distutils directly, ensure that setuptools is installed in the traditional way (e.g. not an editable install), and/or make sure that setuptools is always imported before distutils.
  warnings.warn(
/Users/oliverwm/miniconda3/envs/fv3net/lib/python3.8/site-packages/_distutils_hack/__init__.py:30: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")
Traceback (most recent call last):
  File "/Users/oliverwm/miniconda3/envs/fv3net/bin/pip-compile", line 8, in <module>
    sys.exit(cli())
  File "/Users/oliverwm/miniconda3/envs/fv3net/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/Users/oliverwm/miniconda3/envs/fv3net/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/Users/oliverwm/miniconda3/envs/fv3net/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/oliverwm/miniconda3/envs/fv3net/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/Users/oliverwm/miniconda3/envs/fv3net/lib/python3.8/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/oliverwm/miniconda3/envs/fv3net/lib/python3.8/site-packages/piptools/scripts/compile.py", line 393, in cli
    dist = run_setup(src_file)
  File "/Users/oliverwm/miniconda3/envs/fv3net/lib/python3.8/distutils/core.py", line 215, in run_setup
    exec(f.read(), g)
  File "<string>", line 6, in <module>
  File "/Users/oliverwm/miniconda3/envs/fv3net/lib/python3.8/site-packages/setuptools/__init__.py", line 8, in <module>
    import _distutils_hack.override  # noqa: F401
  File "/Users/oliverwm/miniconda3/envs/fv3net/lib/python3.8/site-packages/_distutils_hack/override.py", line 1, in <module>
    __import__('_distutils_hack').do_override()
  File "/Users/oliverwm/miniconda3/envs/fv3net/lib/python3.8/site-packages/_distutils_hack/__init__.py", line 72, in do_override
    ensure_local_distutils()
  File "/Users/oliverwm/miniconda3/envs/fv3net/lib/python3.8/site-packages/_distutils_hack/__init__.py", line 59, in ensure_local_distutils
    assert '_distutils' in core.__file__, core.__file__
AssertionError: /Users/oliverwm/miniconda3/envs/fv3net/lib/python3.8/distutils/core.py
```

**Comment by oliverwm1** [comment]
`export SETUPTOOLS_USE_DISTUTILS=stdlib` before calling `make lock_pip` resolves the issue.

https://github.com/pypa/setuptools/issues/3044#issuecomment-1024972548

**Comment by oliverwm1** [comment]
@nbren12 I tried creating a fresh fv3net env and still ran into the above issue, unless I set the env var as described above. 

Anyone else run into this?

**Comment by nbren12** [comment]
What is your pip version?

**Comment by nbren12** [comment]
We don't lock setuptools (pip-compile says it's not safe). What is your setuptools version?

**Comment by nbren12** [comment]
Here is mine:
```
$ python3 -c 'import setuptools;print(setuptools.version.__version__)'
59.8.0
```

**Comment by oliverwm1** [comment]
> python3 -c 'import setuptools;print(setuptools.version.__version__)'

Mine is 62.2.0. That's probably the difference.

**Comment by nbren12** [comment]
We could pin the version in the environment.yml.

**Comment by brianhenn** [comment]
+1 my vm conda env also ended up with setuptools 62.2.0 and sent me here
