### ISSUE TITLE
Movie step sometimes fails

### ISSUE THREAD

**Issue by oliverwm1** [ai2cm/fv3net#1997]
On some prognostic run jobs the "movie" step fails. This also means that the single-run prognostic report is not created, even though it does not require the movies.

Steps to reproduce the problem:
- call `prognostic_run_diags movie --n_timesteps 2 --n_jobs 2 gs://vcm-ml-experiments/claytons/2022-08-10/oos-full-year-sweep-ocsvm-tq-larger-gamma-0.5-default-trial1/fv3gfs_run output` and the water vapor path movie fails

Traceback:
```
2022-08-11 11:40:55.297 INFO    fv3net.diagnostics.prognostic_run.views.movies: Forcing load for required variables for water_vapor_path movie
  File "/opt/conda/envs/fv3net/lib/python3.8/site-packages/numpy/lib/nanfunctions.py", line 434, in nanmax
  File "<__array_function__ internals>", line 5, in nanmax
    result = getattr(npmodule, name)(values, axis=axis, **kwargs)
  File "/opt/conda/envs/fv3net/lib/python3.8/site-packages/xarray/core/nputils.py", line 152, in f
    return module.nanmax(a, axis=axis)
  File "/opt/conda/envs/fv3net/lib/python3.8/site-packages/xarray/core/nanops.py", line 91, in nanmax
    return func(values, axis=axis, **kwargs)
  File "/opt/conda/envs/fv3net/lib/python3.8/site-packages/xarray/core/duck_array_ops.py", line 352, in f
    data = func(self.data, **kwargs)
  File "/opt/conda/envs/fv3net/lib/python3.8/site-packages/xarray/core/variable.py", line 1758, in reduce
    var = self.variable.reduce(func, dim, axis, keep_attrs, keepdims, **kwargs)
  File "/opt/conda/envs/fv3net/lib/python3.8/site-packages/xarray/core/dataarray.py", line 2676, in reduce
    return self.reduce(func, dim, axis, skipna=skipna, **kwargs)
  File "/opt/conda/envs/fv3net/lib/python3.8/site-packages/xarray/core/common.py", line 56, in wrapped_func
    if variable in ds and abs(ds[variable]).max() > tol:
  File "/home/jovyan/fv3net/workflows/diagnostics/fv3net/diagnostics/prognostic_run/views/movies.py", line 123, in _non_zero
    if _non_zero(data, required_variables):
  File "/home/jovyan/fv3net/workflows/diagnostics/fv3net/diagnostics/prognostic_run/views/movies.py", line 155, in _create_movie
    _create_movie(movie_spec, dataset, args.output, args.n_jobs)
  File "/home/jovyan/fv3net/workflows/diagnostics/fv3net/diagnostics/prognostic_run/views/movies.py", line 265, in main
    args.func(dissoc(args, "func"))
  File "/home/jovyan/fv3net/workflows/diagnostics/fv3net/diagnostics/prognostic_run/cli.py", line 47, in main
    sys.exit(load_entry_point('fv3net-diagnostics', 'console_scripts', 'prognostic_run_diags')())
  File "/opt/conda/envs/fv3net/bin/prognostic_run_diags", line 33, in <module>
Traceback (most recent call last):
    res = np.fmax.reduce(a, axis=axis, out=out, **kwargs)
ValueError: zero-size array to reduction operation fmax which has no identity
```

**Comment by oliverwm1** [comment]
This is happening because the water vapor path movie requires a verification dataset, and the above run needs the PIRE verification data instead of the default verif data (if i provide `--verification 1yr_pire_postspinup` it works okay).

Furthermore, the argo template for generating movies does not allow providing a custom verification tag/url: https://github.com/ai2cm/fv3net/blob/8b937e1dd3e741c19af0fb6a2a4a4616b9e6f2fd/workflows/argo/prognostic_run_diags.yaml#L187

Don't think we want to simply pass along the `online-diags-flags` parameter to the movie step, since the `prognostic_run_diags save` CLI does not have exactly the same set of arguments as the `prognostic_run_diags movie` CLI.
