### ISSUE TITLE
auth issue for prognostic run tests with user account credentials

### ISSUE THREAD

**Issue by oliverwm1** [ai2cm/fv3net#2028]
If I try to run the prognostic run regression tests locally on my Mac (which uses user account credentials) I get the following error:

```
ERROR:gcsfs:_request out of retries on exception: ('invalid_grant: Bad Request', {'error': 'invalid_grant', 'error_description': 'Bad Request'})
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/gcsfs/retry.py", line 115, in retry_request
    return await func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/gcsfs/core.py", line 368, in _request
    headers=self._get_headers(headers),
  File "/usr/local/lib/python3.8/dist-packages/gcsfs/core.py", line 347, in _get_headers
    self.credentials.apply(out)
  File "/usr/local/lib/python3.8/dist-packages/gcsfs/credentials.py", line 169, in apply
    self.maybe_refresh()
  File "/usr/local/lib/python3.8/dist-packages/gcsfs/credentials.py", line 164, in maybe_refresh
    self.credentials.refresh(req)
  File "/usr/local/lib/python3.8/dist-packages/google/oauth2/credentials.py", line 293, in refresh
    ) = reauth.refresh_grant(
  File "/usr/local/lib/python3.8/dist-packages/google/oauth2/reauth.py", line 338, in refresh_grant
    _client._handle_error_response(response_data)
  File "/usr/local/lib/python3.8/dist-packages/google/oauth2/_client.py", line 60, in _handle_error_response
    raise exceptions.RefreshError(error_details, response_data)
google.auth.exceptions.RefreshError: ('invalid_grant: Bad Request', {'error': 'invalid_grant', 'error_description': 'Bad Request'})
Traceback (most recent call last):
  File "/usr/local/bin/runfv3", line 11, in <module>
    load_entry_point('prognostic-run', 'console_scripts', 'runfv3')()
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/fv3net/workflows/prognostic_c48_run/runtime/segmented_run/cli.py", line 57, in append
    sys.exit(api.append(url))
  File "/fv3net/workflows/prognostic_c48_run/runtime/segmented_run/append.py", line 66, in append_segment_to_run_url
    exit_code = run_segment(config, rundir)
  File "/fv3net/workflows/prognostic_c48_run/runtime/segmented_run/run.py", line 27, in run_segment
    fv3config.write_run_directory(config, rundir)
  File "/usr/local/lib/python3.8/dist-packages/fv3config/config/rundir.py", line 22, in write_run_directory
    write_assets_to_directory(config, target_directory)
  File "/usr/local/lib/python3.8/dist-packages/fv3config/_asset_list.py", line 257, in write_assets_to_directory
    asset_list = config_to_asset_list(config)
  File "/usr/local/lib/python3.8/dist-packages/fv3config/_asset_list.py", line 285, in config_to_asset_list
    asset_list += get_initial_conditions_asset_list(config)
  File "/usr/local/lib/python3.8/dist-packages/fv3config/_asset_list.py", line 64, in get_initial_conditions_asset_list
    source_directory = get_initial_conditions_directory(config)
  File "/usr/local/lib/python3.8/dist-packages/fv3config/_datastore.py", line 82, in get_initial_conditions_directory
    ensure_exists(config["initial_conditions"], "initial_conditions")
  File "/usr/local/lib/python3.8/dist-packages/fv3config/_datastore.py", line 87, in ensure_exists
    if not filesystem.get_fs(location).exists(location):
  File "/usr/local/lib/python3.8/dist-packages/fsspec/asyn.py", line 91, in wrapper
    return sync(self.loop, func, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/fsspec/asyn.py", line 71, in sync
    raise return_result
  File "/usr/local/lib/python3.8/dist-packages/fsspec/asyn.py", line 25, in _runner
    result[0] = await coro
  File "/usr/local/lib/python3.8/dist-packages/fsspec/asyn.py", line 549, in _exists
    await self._info(path)
  File "/usr/local/lib/python3.8/dist-packages/gcsfs/core.py", line 674, in _info
    return await self._get_object(path)
  File "/usr/local/lib/python3.8/dist-packages/gcsfs/core.py", line 452, in _get_object
    res = await self._call("GET", "b/{}/o/{}", bucket, key, json_out=True)
  File "/usr/local/lib/python3.8/dist-packages/gcsfs/core.py", line 386, in _call
    status, headers, info, contents = await self._request(
  File "<decorator-gen-2>", line 2, in _request
  File "/usr/local/lib/python3.8/dist-packages/gcsfs/retry.py", line 147, in retry_request
    raise e
  File "/usr/local/lib/python3.8/dist-packages/gcsfs/retry.py", line 115, in retry_request
    return await func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/gcsfs/core.py", line 368, in _request
    headers=self._get_headers(headers),
  File "/usr/local/lib/python3.8/dist-packages/gcsfs/core.py", line 347, in _get_headers
    self.credentials.apply(out)
  File "/usr/local/lib/python3.8/dist-packages/gcsfs/credentials.py", line 169, in apply
    self.maybe_refresh()
  File "/usr/local/lib/python3.8/dist-packages/gcsfs/credentials.py", line 164, in maybe_refresh
    self.credentials.refresh(req)
  File "/usr/local/lib/python3.8/dist-packages/google/oauth2/credentials.py", line 293, in refresh
    ) = reauth.refresh_grant(
  File "/usr/local/lib/python3.8/dist-packages/google/oauth2/reauth.py", line 338, in refresh_grant
    _client._handle_error_response(response_data)
  File "/usr/local/lib/python3.8/dist-packages/google/oauth2/_client.py", line 60, in _handle_error_response
    raise exceptions.RefreshError(error_details, response_data)
google.auth.exceptions.RefreshError: ('invalid_grant: Bad Request', {'error': 'invalid_grant', 'error_description': 'Bad Request'})
```

I do not get this if running on my VM which is currently using service account credentials.

Steps to reproduce:
- `make build_image_prognostic_run`
- `make enter_prognostic_run`
- `pytest tests/test_regression.py`

**Comment by oliverwm1** [comment]
I can reproduce this by calling `python3 -c "import fsspec; fsspec.filesystem('gs').ls('vcm-fv3config')"` in the prognostic run image. Also get it if using a bucket that is not requester pays. Using `gsutil ls` works fine.

**Comment by oliverwm1** [comment]
I think this is just a problem with my user account based auth, independent of the prognostic run image, so I'm closing the issue.
