### ISSUE TITLE
`module load python/3.9` on Gaea introduces conflicting ESMF library into `LD_LIBRARY_PATH`

### ISSUE THREAD

**Issue by spencerkclark** [ai2cm/fv3net#2074]
This is a related issue to the one cited in https://github.com/ai2cm/fv3net/pull/2047#discussion_r978154605.  I will bring this up to GFDL as well.  

```
Traceback (most recent call last):
  File "/lustre/f2/dev/Spencer.Clark/2022-09-29-fv3net-environment/install/conda/envs/2022-09-29-prognostic-run/bin/prepare-config", line 33, in <module>
    sys.exit(load_entry_point('prognostic-run', 'console_scripts', 'prepare-config')())
  File "/lustre/f2/dev/Spencer.Clark/2022-09-29-fv3net-environment/install/conda/envs/2022-09-29-prognostic-run/bin/prepare-config", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/lustre/f2/dev/Spencer.Clark/2022-09-29-fv3net-environment/install/conda/envs/2022-09-29-prognostic-run/lib/python3.8/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/lustre/f2/dev/Spencer.Clark/2022-09-29-fv3net-environment/install/conda/envs/2022-09-29-prognostic-run/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/lustre/f2/dev/Spencer.Clark/2022-09-29-fv3net/fv3net/workflows/prognostic_c48_run/runtime/__init__.py", line 1, in <module>
    from .config import get_namelist, get_config, write_chunks
  File "/lustre/f2/dev/Spencer.Clark/2022-09-29-fv3net/fv3net/workflows/prognostic_c48_run/runtime/config.py", line 13, in <module>
    from runtime.steppers.nudging import NudgingConfig
  File "/lustre/f2/dev/Spencer.Clark/2022-09-29-fv3net/fv3net/workflows/prognostic_c48_run/runtime/steppers/nudging.py", line 4, in <module>
    import fv3gfs.wrapper
  File "/lustre/f2/dev/Spencer.Clark/2022-09-29-fv3net-environment/install/conda/envs/2022-09-29-prognostic-run/lib/python3.8/site-packages/fv3gfs/wrapper/__init__.py", line 2, in <module>
    from ._wrapper import (
ImportError: /ncrc/sw/gaea-cle7/python/3.9/anaconda-base/envs/noaa_py3.9/lib/libesmf.so: undefined symbol: __netcdf_MOD_nf90_put_var_1d_fourbyteint
```

**Comment by spencerkclark** [comment]
I received word from ORNL that they will not add a "conda" module that just loads the command line tool and nothing else.  While I was hopeful we could avoid the workaround that prompted https://github.com/ai2cm/fv3net/pull/2047#discussion_r978154605, I think I will need to formalize it for now in this repo.
