### ISSUE TITLE
`make enter_prognostic_run` results in environment that can no longer import the Python wrapper

### ISSUE THREAD

**Issue by spencerkclark** [ai2cm/fv3net#2080]
#2047 resulted in FMS and FV3GFS being compiled directly in the `external/fv3gfs-fortran` directory.  Previously both of these steps were done in directories outside `external`.  This enabled bind-mounting the user's full local fv3net `external` directory into the image in the `enter_prognostic_run` rule of the fv3net Makefile, without interfering with linking to libraries that were built within the image (e.g. FMS).  The current behavior causes problems, because one will not have compiled FMS or FV3GFS within their local fv3net clone.  Therefore importing the wrapper fails:
```
root@14fd0a7294de:/fv3net/workflows/prognostic_c48_run# python3 -c "from fv3gfs import wrapper"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.8/dist-packages/fv3gfs/wrapper/__init__.py", line 2, in <module>
    from ._wrapper import (
ImportError: libFMS.so.2: cannot open shared object file: No such file or directory
```
A simple fix would be to restore the behavior of compiling FMS and FV3GFS in a location outside of `external`.

**Comment by spencerkclark** [comment]
I found a simpler fix.  We can just override the mount for the `fv3gfs-fortran` directory specifically, and let the others pass through undisturbed.  See #2093.
