### ISSUE TITLE
Error when running a nudged run with reference_initial_time and reference_frequency_seconds set

### ISSUE THREAD

**Issue by spencerkclark** [ai2cm/fv3net#889]
Using the prognostic run workflow if one explicitly sets `nudging.reference_initial_time` and `nudging.reference_frequency_seconds` in their config file, the nudged run crashes when computing diagnostics:

<details>
<p>

```
Traceback (most recent call last):
  File "/mnt/data/runfile.py", line 596, in <module>
    comm, diagnostics, exclude=loop._states_to_output
  File "/mnt/data/runfile.py", line 557, in globally_average_2d_diagnostics
    if (set(diagnostics[v].dims) == {"x", "y"}) and (v not in exclude):
AttributeError: 'cftime._cftime.DatetimeJulian' object has no attribute 'dims'
Traceback (most recent call last):
  File "/mnt/data/runfile.py", line 596, in <module>
    comm, diagnostics, exclude=loop._states_to_output
  File "/mnt/data/runfile.py", line 557, in globally_average_2d_diagnostics
    if (set(diagnostics[v].dims) == {"x", "y"}) and (v not in exclude):
AttributeError: 'cftime._cftime.DatetimeJulian' object has no attribute 'dims'
Traceback (most recent call last):
  File "/mnt/data/runfile.py", line 596, in <module>
    comm, diagnostics, exclude=loop._states_to_output
  File "/mnt/data/runfile.py", line 557, in globally_average_2d_diagnostics
    if (set(diagnostics[v].dims) == {"x", "y"}) and (v not in exclude):
AttributeError: 'cftime._cftime.DatetimeJulian' object has no attribute 'dims'
Traceback (most recent call last):
  File "/mnt/data/runfile.py", line 596, in <module>
    comm, diagnostics, exclude=loop._states_to_output
  File "/mnt/data/runfile.py", line 557, in globally_average_2d_diagnostics
    if (set(diagnostics[v].dims) == {"x", "y"}) and (v not in exclude):
AttributeError: 'cftime._cftime.DatetimeJulian' object has no attribute 'dims'
Traceback (most recent call last):
  File "/mnt/data/runfile.py", line 596, in <module>
    comm, diagnostics, exclude=loop._states_to_output
  File "/mnt/data/runfile.py", line 557, in globally_average_2d_diagnostics
    if (set(diagnostics[v].dims) == {"x", "y"}) and (v not in exclude):
AttributeError: 'cftime._cftime.DatetimeJulian' object has no attribute 'dims'
Traceback (most recent call last):
  File "/mnt/data/runfile.py", line 596, in <module>
    comm, diagnostics, exclude=loop._states_to_output
  File "/mnt/data/runfile.py", line 557, in globally_average_2d_diagnostics
    if (set(diagnostics[v].dims) == {"x", "y"}) and (v not in exclude):
AttributeError: 'cftime._cftime.DatetimeJulian' object has no attribute 'dims'

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   PID 42 RUNNING AT prognostic-run-shcqv-311161833
=   EXIT CODE: 1
=   CLEANING UP REMAINING PROCESSES
=   YOU CAN IGNORE THE BELOW CLEANUP MESSAGES
===================================================================================
```

<p>
</details>

This likely has something to do with a difference in the structure of the state returned by these different implementations of `_get_reference_state`:
https://github.com/VulcanClimateModeling/fv3net/blob/0768c9e95edee786cd7b5776d9225b937880b381/workflows/prognostic_c48_run/runtime/nudging.py#L58-L74

https://github.com/VulcanClimateModeling/fv3net/blob/0768c9e95edee786cd7b5776d9225b937880b381/workflows/prognostic_c48_run/runtime/nudging.py#L102-L131

These options are used when running a simulation where the frequency of the nudging data does not match up with the timestep of the model.

**Comment by spencerkclark** [comment]
I don't remember the context for why the PR that fixed this was closed (#899), but perhaps it means that this issue was not relevant any more.  Regardless, I've run several nudged runs since this issue was posted with 25-km reference data, and this issue has not come up, so I think this can be closed.
